function stat = get_clusters(wfa,coeff,cut_off)
c = correlation(wfa);
c = crop(c,-2,5);
c = taper(c);
c = butter(c,[1 10]);
c = xcorr(c);
c = sort(c);
c = adjusttrig(c,'MIN');
c = linkage2(c);
c = cluster(c,coeff);
stat = getclusterstat(c);
cut = find(stat.numel<cut_off);
stat.rank(cut)=[];
stat.numel(cut)=[];
stat.index(cut)=[];
stat.begin(cut)=[];
stat.finish(cut)=[];
stat.trig(cut)=[];