
%%
figure, hold on
R = log(E.rms);
%R(end+1)=R(end);
color = [0 0 0];
line([1 1],[max(R(P.pre)) min(R(P.pre))],'color',color)
line([2 2],[max(R(S.T1)) min(R(S.T1))],'color',color)
line([3 3],[max(R(S.T2)) min(R(S.T2))],'color',color)
line([4 4],[max(R(S.S2)) min(R(S.S2))],'color',color)
line([5 5],[max(R(S.P1)) min(R(S.P1))],'color',color)
line([6 6],[max(R(P.exp)) min(R(P.exp))],'color',color)
line([7 7],[max(R(S.P2)) min(R(S.P2))],'color',color)
line([8 8],[max(R(S.S2)) min(R(S.S2))],'color',color)
line([9 9],[max(R(S.P3)) min(R(S.P3))],'color',color)
line([10 10],[max(R(P.con)) min(R(P.con))],'color',color)
line([11 11],[max(R(S.S3)) min(R(S.S3))],'color',color)

scatter(1:11,[max(R(P.pre)) max(R(S.T1)) max(R(S.T2)) max(R(S.S2)) ...
              max(R(S.P1)) max(R(P.exp)) max(R(S.P2)) max(R(S.S2)) ...
              max(R(S.P3)) max(R(P.con)) max(R(S.S3))],...
              'Marker','^','MarkerEdgeColor',color,'MarkerFaceColor',[1 1 1])
           
scatter(1:11,[mean(R(P.pre)) mean(R(S.T1)) mean(R(S.T2)) mean(R(S.S2)) ...
              mean(R(S.P1)) mean(R(P.exp)) mean(R(S.P2)) mean(R(S.S2)) ...
              mean(R(S.P3)) mean(R(P.con)) mean(R(S.S3))],...   
           'Marker','square','MarkerEdgeColor',color,'MarkerFaceColor',[1 1 1])
           
scatter(1:11,[median(R(P.pre)) median(R(S.T1)) median(R(S.T2)) median(R(S.S2)) ...
              median(R(S.P1)) median(R(P.exp)) median(R(S.P2)) median(R(S.S2)) ...
              median(R(S.P3)) median(R(P.con)) median(R(S.S3))],...    
           'Marker','o','MarkerEdgeColor',color,'MarkerFaceColor',[1 1 1])
        
scatter(1:11,[min(R(P.pre)) min(R(S.T1)) min(R(S.T2)) min(R(S.S2)) ...
              min(R(S.P1)) min(R(P.exp)) min(R(S.P2)) min(R(S.S2)) ...
              min(R(S.P3)) min(R(P.con)) min(R(S.S3))],...     
           'Marker','v','MarkerEdgeColor',color,'MarkerFaceColor',[1 1 1])
xlim([0 12])           